### ISSUE TITLE
Strange external processes spawned

### ISSUE THREAD

**Issue by jjlauer** [thrau/jarchivelib#49] opened 2016-04-02 13:23 UTC
Was having an issue on linux where my maven process wouldn't properly finish.  After digging a couple hours, it looked like extra threads were being spun up and not properly cleaned up.  Unfortunately, the root cause was jarchivelib.  Didn't have the issue on windows.  After digging thru your code, I suspects its the spinning up of "chmod" as an external process to apply permissions.  Java 7 has pretty awesome support for properly setting posix permissions all in Java.  No need for an external process.  I reverted back to Apache commons compress for now, but wanted to give you a heads up on the issue.

**Comment by thrau** [comment] 2016-04-02 13:59
The particular piece of code you are referring to is not actually used. Modes are set via a reflective call to `java.utils.pref.FileSystemPreferences#chmod`, see [here](https://github.com/thrau/jarchivelib/blob/master/src/main/java/org/rauschig/jarchivelib/FileModeMapper.java#L139).

Yes. The blissful world of Java 7 nio. It's on the list #22  ;-)

However to the problem at hand: Maybe you could explain in more detail what it is you are executing so I can reproduce it.

**Comment by jjlauer** [comment] 2016-04-02 14:11
To reproduce:

 - Run it on linux. Did not occur on Windows.
 - Uncompress either a .zip or .tar.gz into a directory.
 - If you use maven and the exec:java plugin, you'll notice how the app
doesn't actually exit cleanly.  Maven waits 15 seconds, then complains
about non-daemon threads.
 - Alternative to maven exex:java. In your own main method, do the above,
but don't let app exit, I used a simple Thread.sleep(10000000L).  Then open
up jvisualvm.  You'll see a "Timer-0" thread.  That's the problem.  Its a
non-daemon thread, somehow created by whatever is happening above.  The
stacktrace of this thread is utterly useless and why it took me a few hours
to drive down to the root cause.

**Comment by thrau** [comment] 2016-10-16 11:58
i finally had the chance to have a look at it. debugging through the steps until the thread spanwed showed that it's caused by the reflective call to the native method `java.util.prefs.FileSystemPreferences#chmod`. i don't really see what i could do about this, as the thread is spawned by the underlying native implementation. a normal runtime exit closes the thread normally. the only immediate solution i see is to revert to `Runtime.getRuntime().exec("chmod ...")` for setting modes, which i would like to avoid.

if you have any suggestions, please share

**Comment by thrau** [comment] 2017-09-21 11:50
closing this - this won't fix until the major rework.

**Closed by thrau** 2017-09-21 11:50 UTC
Labels: wontfix
